services:
  - name: laravel-api
    type: web
    env: docker
    plan: free  # Cambia esto dependiendo del plan que elijas
    dockerfilePath: ./vendor/laravel/sail/runtimes/8.3/Dockerfile
    dockerCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_NAME
        value: ForstAI
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GFeuclP/oDjB+7FSc4fgGSoLicKX7517A4quetZ9i6E=
      - key: APP_DEBUG
        value: 'true'
      - key: APP_URL
        value: http://localhost:8000
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: laravel-api-db
      - key: DB_PORT
        value: '3306'
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: sail
      - key: DB_PASSWORD
        value: password
      - key: BROADCAST_DRIVER
        value: pusher
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: '120'
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: '6379'
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: '587'
      - key: MAIL_USERNAME
        value: victor01val@gmail.com
      - key: MAIL_PASSWORD
        value: 'ceog zxpe nqgk agqw'
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: victor01val@gmail.com
      - key: MAIL_FROM_NAME
        value: ForstAI
      - key: AWS_ACCESS_KEY_ID
        value: ''
      - key: AWS_SECRET_ACCESS_KEY
        value: ''
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ''
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: 'false'
      - key: PUSHER_APP_ID
        value: '1789774'
      - key: PUSHER_APP_KEY
        value: '8e538abdf712b17d5124'
      - key: PUSHER_APP_SECRET
        value: 'c5a8ce31e569b80c5250'
      - key: PUSHER_PORT
        value: '443'
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_APP_CLUSTER
        value: eu
      - key: VITE_APP_NAME
        value: ForstAI
      - key: VITE_PUSHER_APP_KEY
        value: '8e538abdf712b17d5124'
      - key: VITE_PUSHER_HOST
        value: ''
      - key: VITE_PUSHER_PORT
        value: '443'
      - key: VITE_PUSHER_SCHEME
        value: https
      - key: VITE_PUSHER_APP_CLUSTER
        value: eu
      - key: SESSION_DOMAIN
        value: localhost
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost
    ports:
      - containerPort: 10000
        protocol: tcp
    healthCheckPath: "/health"  # Cambia esto dependiendo de tu ruta de verificación de salud

  - name: laravel-api-db
    type: db
    plan: starter
    databaseName: laravel
    user: sail
    password: password
